baseURL = 'https://weifengdel0ng.github.io/'
languageCode = 'zh-cn'
title = '微风的龙'
theme = 'hugo-theme-bootstrap'
enableRobotsTXT = true
hasCJKLanguage = true

[build]
writeStats = true

[params]
description = '微风的龙的个人博客，记录技术、项目和思考。'
keywords = '博客, Hugo, PWN, BUUOJ, 个人主页'
logo = false
mainSections = ['posts']
breadCrumb = false
socialShare = false
searchBar = true
color = 'auto'

[menu]

[[menu.main]]
name = '首页'
url = '/'
weight = 1

[[menu.main]]
name = '文章'
url = '/posts/'
weight = 2

[[menu.main]]
name = '关于'
url = '/about/'
weight = 3

[params.author]
name = '微风的龙'
avatar = 'images/profile.png'
bio = '哈基龙的个人博客，看看得了'
location = 'China'
about = 'https://github.com/weifengdel0ng'

[params.author.social]
github = 'weifengdel0ng'
